version: '3.8'

services:
  couchdb:
    image: couchdb:3.3
    container_name: couchdb-dev
    environment:
      - COUCHDB_USER=${COUCHDB_USER:-admin}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD:-password}
    ports:
      - "${COUCHDB_PORT:-5984}:5984"
    volumes:
      - couchdb_data:/opt/couchdb/data
      - couchdb_config:/opt/couchdb/etc
      - ./local.ini:/opt/couchdb/etc/local.d/local.ini
    restart: unless-stopped
    networks:
      - couchdb_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5984/_up"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  couchdb_data:
    driver: local
  couchdb_config:
    driver: local

networks:
  couchdb_network:
    driver: bridge
